package com.example.mainproject

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TextField
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController
import coil.compose.AsyncImage
import java.util.UUID
import kotlin.random.Random

data class FilmModel(
    val id: String,
    val posterUrl: String,
    val name: String,
    val description: String?,
    val releaseDate: Int
)

object DataRepository {
    var filmsList: List<FilmModel> = emptyList()
}

class MainActivity2 : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MaterialTheme {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    AppNavigation()
                }
            }
        }
    }
}

@Composable
fun AppNavigation() {
    val navController = rememberNavController()

    NavHost(
        navController = navController,
        startDestination = "first_screen"
    ) {
        composable("first_screen") {
            FirstScreen(
                onNavigateToSecond = {
                    navController.navigate("second_screen")
                }
            )
        }
        composable("second_screen") {
            SecondScreen()
        }
    }
}

@Composable
fun FirstScreen(onNavigateToSecond: () -> Unit) {
    var inputText by remember { mutableStateOf("") }
    var isListGenerated by remember { mutableStateOf(false) }

    val isGenerateEnabled = inputText.isNotEmpty() && (inputText.toIntOrNull() ?: 0) > 0

    val movieNames = listOf(
        "Shutter Island", "Inception", "Blood diamond", "Snatch",
        "The Matrix", "Interstellar", "Gladiator", "The Dark Knight",
        "Fight Club", "Pulp Fiction", "Avatar", "The Green Mile"
    )
    val posters = listOf(
        "https://unsplash.com",
        "https://unsplash.com",
        "https://unsplash.com"
    )

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(24.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        TextField(
            value = inputText,
            onValueChange = { newValue ->
                if (newValue.all { it.isDigit() }) {
                    inputText = newValue
                }
            },
            label = { Text("Размер списка") },
            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
            singleLine = true,
            modifier = Modifier.fillMaxWidth()
        )

        Spacer(modifier = Modifier.height(24.dp))

        Button(
            onClick = {
                val size = inputText.toIntOrNull() ?: 0
                val generatedList = List(size) {
                    FilmModel(
                        id = UUID.randomUUID().toString(),
                        posterUrl = posters[Random.nextInt(posters.size)],
                        name = movieNames[Random.nextInt(movieNames.size)] + " ${Random.nextInt(1, 4)}",
                        description = "Описание фильма",
                        releaseDate = Random.nextInt(1995, 2026)
                    )
                }
                DataRepository.filmsList = generatedList
                isListGenerated = true
            },
            enabled = isGenerateEnabled,
            modifier = Modifier.fillMaxWidth()
        ) {
            Text("Сгенерировать")
        }

        Spacer(modifier = Modifier.height(16.dp))

        Button(
            onClick = onNavigateToSecond,
            enabled = isListGenerated,
            modifier = Modifier.fillMaxWidth()
        ) {
            Text("Открыть второй экран")
        }
    }
}

@Composable
fun SecondScreen() {
    var filterText by remember { mutableStateOf("") }
    var displayedList by remember { mutableStateOf(DataRepository.filmsList) }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp)
    ) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            verticalAlignment = Alignment.CenterVertically
        ) {
            TextField(
                value = filterText,
                onValueChange = { newValue ->
                    if (newValue.all { it.isDigit() }) {
                        filterText = newValue
                    }
                },
                label = { Text("Год выпуска (<=)") },
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                singleLine = true,
                modifier = Modifier.weight(1f)
            )

            Spacer(modifier = Modifier.width(8.dp))

            Button(
                onClick = {
                    if (filterText.isEmpty()) {
                        displayedList = DataRepository.filmsList
                    } else {
                        val targetYear = filterText.toIntOrNull()
                        displayedList = if (targetYear != null) {
                            DataRepository.filmsList.filter { it.releaseDate <= targetYear }
                        } else {
                            DataRepository.filmsList
                        }
                    }
                }
            ) {
                Text("Сортировать")
            }
        }

        Spacer(modifier = Modifier.height(16.dp))

        if (displayedList.isEmpty()) {
            Box(
                modifier = Modifier.fillMaxSize(),
                contentAlignment = Alignment.Center
            ) {
                Text(
                    text = "Нет данных, соответствующих запросу",
                    fontSize = 16.sp,
                    color = MaterialTheme.colorScheme.error
                )
            }
        } else {
            LazyColumn(
                modifier = Modifier.fillMaxSize(),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                items(displayedList) { film ->
                    FilmItem(film = film)
                }
            }
        }
    }
}

@Composable
fun FilmItem(film: FilmModel) {
    Row(
        modifier = Modifier.fillMaxWidth(),
        verticalAlignment = Alignment.CenterVertically
    ) {
        AsyncImage(
            model = film.posterUrl,
            contentDescription = null,
            modifier = Modifier
                .size(width = 60.dp, height = 90.dp)
        )

        Spacer(modifier = Modifier.width(16.dp))

        Column {
            Text(
                text = film.name,
                fontSize = 18.sp,
                style = MaterialTheme.typography.titleMedium
            )
            Spacer(modifier = Modifier.height(4.dp))
            Text(
                text = "Год: ${film.releaseDate}",
                fontSize = 14.sp,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
        }
    }
}
